# Generated by Django 5.0.1 on 2024-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dish_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_cart',
            name='ammount',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
