# Generated by Django 5.0.1 on 2024-02-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
